/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.torneo_kiljoy.vista;

import com.torneo_kiljoy.controlador.ControladorLista1;
import com.torneo_kiljoy.controlador.ControladorLista2;
import com.torneo_kiljoy.controlador.ControladorUsuario;
import com.torneo_kiljoy.excepciones.UsuarioExcepcion;
import com.torneo_kiljoy.modelo.Aspirante;
import com.torneo_kiljoy.modelo.Participante;
import com.torneo_kiljoy.modelo.Usuario;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAURA MELISSA
 */
public class MDIKiljoy extends javax.swing.JFrame {

    private ControladorUsuario controlUsuarios;
    private Usuario usuarioAutenticado;
    private ControladorLista1 controlLista1;
    private ControladorLista2 controlLista2;

    /**
     * Creates new form NewMDIApplication
     */
    public MDIKiljoy() {
        initComponents(); //Crea todas las instancias
        controlarEstadoMenus();
        controlUsuarios = new ControladorUsuario();
        controlLista1 = new ControladorLista1();
        controlLista2 = new ControladorLista2();
        txtCorreo.setText("meli@gmail.com");
        txtContrasenia.setText("123456");
        llenarAspirantes();
        llenarParticipantes();
        
    }

    private void llenarAspirantes() {
        DefaultTableModel model = (DefaultTableModel) tblAspirantes.getModel();
        model.getDataVector().removeAllElements();
//        Object[] fila = {"Laura","killjoy","pink",(byte)18,(long)56421325};
//        model.addRow(fila);
        for (Aspirante asp : controlLista1.getAspirantes()) {
            if (asp != null) {
                Object[] fila = {asp.getNombre(), asp.obtenerCodigo(asp.getNickname()), asp.getNickname(), asp.getEdad(), asp.getPuntuacion()};

                model.addRow(fila);
            }
        }
        tblAspirantes.repaint();

    }
    private void llenarParticipantes(){
        DefaultTableModel model = (DefaultTableModel) tblParticipantes.getModel();
        model.getDataVector().removeAllElements();
        
        for(Participante part : controlLista2.getParticipantes()){
            if(part != null){
                Object[] fila = {part.getNombre(),part.obtenerCodigo(part.getNickname()),part.getNickname(),part.getEdad(),part.getPuntuacion()};
                
                model.addRow(fila);
            }
        }
    }

    public void controlarEstadoMenus() {
        mnuAspirantes.setEnabled(false);
        mnuAgregarAspirantes.setEnabled(false);
        mnuParticipantes.setEnabled(false);
        mnuAgregarParticipantes.setEnabled(false);

        if (usuarioAutenticado != null) {
            switch (usuarioAutenticado.getRol().getCodigo()) {
                case 1:
                    mnuAspirantes.setEnabled(true);
                    mnuAgregarAspirantes.setEnabled(true);
                    mnuParticipantes.setEnabled(true);
                    mnuAgregarParticipantes.setEnabled(true);
                    break;
                case 2:
                    mnuAspirantes.setEnabled(true);
                    mnuAgregarAspirantes.setEnabled(true);
                    mnuParticipantes.setEnabled(true);
                    mnuAgregarParticipantes.setEnabled(false);
                    break;
                case 3:
                    mnuAspirantes.setEnabled(true);
                    mnuAgregarAspirantes.setEnabled(false);
                    mnuParticipantes.setEnabled(true);
                    mnuAgregarParticipantes.setEnabled(false);

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifAspirantes = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAspirantes = new javax.swing.JTable();
        jifLogin = new javax.swing.JInternalFrame();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jifParticipantes = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblParticipantes = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivos = new javax.swing.JMenu();
        mnuAspirantes = new javax.swing.JMenuItem();
        mnuAgregarAspirantes = new javax.swing.JMenuItem();
        mnuAgregarParticipantes = new javax.swing.JMenuItem();
        mnuParticipantes = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifAspirantes.setClosable(true);
        jifAspirantes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifAspirantes.setIconifiable(true);
        jifAspirantes.setMaximizable(true);
        jifAspirantes.setResizable(true);
        jifAspirantes.setTitle("Aspirantes");
        jifAspirantes.setVisible(false);

        tblAspirantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAspirantes);

        javax.swing.GroupLayout jifAspirantesLayout = new javax.swing.GroupLayout(jifAspirantes.getContentPane());
        jifAspirantes.getContentPane().setLayout(jifAspirantesLayout);
        jifAspirantesLayout.setHorizontalGroup(
            jifAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifAspirantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jifAspirantesLayout.setVerticalGroup(
            jifAspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifAspirantesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        desktopPane.add(jifAspirantes);
        jifAspirantes.setBounds(30, 30, 230, 260);

        jifLogin.setIconifiable(true);
        jifLogin.setMaximizable(true);
        jifLogin.setTitle("Ingreso ");
        jifLogin.setVisible(true);

        lblUsuario.setText("*Correo:");

        lblContrasenia.setText("*Contrasenia:");

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasenia)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        desktopPane.add(jifLogin);
        jifLogin.setBounds(50, 40, 353, 232);

        jifParticipantes.setClosable(true);
        jifParticipantes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifParticipantes.setIconifiable(true);
        jifParticipantes.setMaximizable(true);
        jifParticipantes.setResizable(true);
        jifParticipantes.setTitle("Participantes");
        jifParticipantes.setVisible(false);

        tblParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Nickname", "Edad", "Puntuación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblParticipantes);

        javax.swing.GroupLayout jifParticipantesLayout = new javax.swing.GroupLayout(jifParticipantes.getContentPane());
        jifParticipantes.getContentPane().setLayout(jifParticipantesLayout);
        jifParticipantesLayout.setHorizontalGroup(
            jifParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jifParticipantesLayout.setVerticalGroup(
            jifParticipantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        desktopPane.add(jifParticipantes);
        jifParticipantes.setBounds(10, 0, 400, 270);

        mnuArchivos.setMnemonic('f');
        mnuArchivos.setText("Inicio");

        mnuAspirantes.setMnemonic('o');
        mnuAspirantes.setText("Aspirantes");
        mnuAspirantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAspirantesActionPerformed(evt);
            }
        });
        mnuArchivos.add(mnuAspirantes);

        mnuAgregarAspirantes.setMnemonic('s');
        mnuAgregarAspirantes.setText("Agregar Aspirantes");
        mnuAgregarAspirantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarAspirantesActionPerformed(evt);
            }
        });
        mnuArchivos.add(mnuAgregarAspirantes);

        mnuAgregarParticipantes.setText("Agregar Participantes");
        mnuAgregarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarParticipantesActionPerformed(evt);
            }
        });
        mnuArchivos.add(mnuAgregarParticipantes);

        mnuParticipantes.setMnemonic('a');
        mnuParticipantes.setText("Participantes");
        mnuParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParticipantesActionPerformed(evt);
            }
        });
        mnuArchivos.add(mnuParticipantes);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivos.add(mnuSalir);

        menuBar.add(mnuArchivos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        JOptionPane.showMessageDialog(rootPane, "ADios lok");
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAspirantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAspirantesActionPerformed
        // TODO add your handling code here:
        jifAspirantes.show();

    }//GEN-LAST:event_mnuAspirantesActionPerformed

    private void mnuAgregarAspirantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarAspirantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAgregarAspirantesActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try {

            usuarioAutenticado = controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContrasenia.getText());
            controlarEstadoMenus();
            jifLogin.hide();

            JOptionPane.showMessageDialog(rootPane, "Bienvenido " + usuarioAutenticado.getNombre(), "Ingreso Exitoso", 1);
        } catch (UsuarioExcepcion ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Eror", 0);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParticipantesActionPerformed
        // TODO add your handling code here:
        jifParticipantes.show();
    }//GEN-LAST:event_mnuParticipantesActionPerformed

    private void mnuAgregarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAgregarParticipantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIKiljoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIKiljoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIKiljoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIKiljoy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIKiljoy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JInternalFrame jifAspirantes;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JInternalFrame jifParticipantes;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAgregarAspirantes;
    private javax.swing.JMenuItem mnuAgregarParticipantes;
    private javax.swing.JMenu mnuArchivos;
    private javax.swing.JMenuItem mnuAspirantes;
    private javax.swing.JMenuItem mnuParticipantes;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTable tblAspirantes;
    private javax.swing.JTable tblParticipantes;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
